import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/navbar/Navbar';
import { ClerkProvider } from '@clerk/nextjs';
import { deDE } from '@clerk/localizations';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Lateininator',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider localization={deDE}>
			<html lang='en'>
				<body className={inter.className}>
					<div className='min-h-screen'>
						<Navbar />
						{children}
					</div>
				</body>
			</html>
		</ClerkProvider>
	);
}
